// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OrderTaker.Models;

[Index("FullName", Name = "Is_Unique_FullName", IsUnique = true)]
[Index("MobileNumber", Name = "Is_Unique_Mobile", IsUnique = true)]
public partial class Customer
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    [Display(Name = "First Name")]
    public string FirstName { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    [Display(Name = "Last Name")]
    public string LastName { get; set; }

    [Required]
    [StringLength(102)]
    [Unicode(false)]
    [Display(Name = "Full Name")]
    public string FullName { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    [RegularExpression("^[0-9]*$", ErrorMessage = "Mobile number must be numeric")]
    [Display(Name = "Mobile Number")]
    public string MobileNumber { get; set; }

    [Required]
    [Unicode(false)]
    public string City { get; set; }

    [Column(TypeName = "datetime")]
    [Display(Name = "Date Created")]
    public DateTime DateCreated { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    [Display(Name = "Created by")]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    [Display(Name = "Date Modified")]
    public DateTime Timestamp { get; set; }

    public string? UserID { get; set; }

    [Required]
    [Display(Name = "Is Active")]
    public bool? IsActive { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; } = new List<PurchaseOrder>();
}