// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OrderTaker.Models;

[Table("PurchaseOrder")]
public partial class PurchaseOrder
{
    [Key]
    public int ID { get; set; }

    public int CustomerID { get; set; }

    [Column(TypeName = "date")]
    [Display(Name = "Date of Delivery"), DataType(DataType.Date)]
    public DateTime DateOfDelivery { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Status { get; set; }

    [DataType(DataType.Currency)]
    [Column(TypeName = "decimal(18, 2)")]
    [Display(Name = "Amount Due")]
    public decimal AmountDue { get; set; }

    [Column(TypeName = "datetime")]
    [Display(Name = "Date Created")]
    public DateTime DateCreated { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    [Display(Name = "Created by")]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    [Display(Name = "Date Modified")]
    public DateTime Timestamp { get; set; }

    public string? UserID { get; set; }

    [Required]
    public bool? IsActive { get; set; }

    [ForeignKey("CustomerID")]
    [InverseProperty("PurchaseOrders")]
    public virtual Customer Customer { get; set; }

    [InverseProperty("PurchaseOrder")]
    public virtual ICollection<PurchaseItem> PurchaseItems { get; set; } = new List<PurchaseItem>();
}

public enum Status
{
    New,
    Completed,
    Cancelled
}