// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OrderTaker.Models;

public partial class PurchaseItem
{
    [Key]
    public int ID { get; set; }

    public int PurchaseOrderID { get; set; }

    public int SKUID { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    [DataType(DataType.Currency)]
    public decimal Price { get; set; }

    [Column(TypeName = "datetime")]
    [Display(Name = "Date Modified")]
    public DateTime Timestamp { get; set; }

    public string? UserID { get; set; }

    [ForeignKey("PurchaseOrderID")]
    [InverseProperty("PurchaseItems")]
    public virtual PurchaseOrder PurchaseOrder { get; set; }

    [ForeignKey("SKUID")]
    [InverseProperty("PurchaseItems")]
    public virtual SKU SKU { get; set; }
}