// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OrderTaker.Models;

[Index("Code", Name = "Is_Unique_CODE", IsUnique = true)]
[Index("Name", Name = "Is_Unique_NAME", IsUnique = true)]
public partial class SKU
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Code { get; set; }

    [DataType(DataType.Currency)]
    [Column(TypeName = "decimal(18, 2)")]
    [Display(Name = "Unit Price")]
    public decimal UnitPrice { get; set; }

    [Column(TypeName = "datetime")]
    [Display(Name = "Date Created")]
    public DateTime DateCreated { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    [Display(Name = "Created by")]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    [Display(Name = "Date Modified")]
    public DateTime Timestamp { get; set; }

    public string? UserID { get; set; }

    [Display(Name = "Is Active")]
    public bool IsActive { get; set; }

    [InverseProperty("SKU")]
    public virtual ICollection<PurchaseItem> PurchaseItems { get; set; } = new List<PurchaseItem>();
}